controllers:
    resource: ../src/Controller/
    type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['GET','POST']

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_avis_new:
    path: /avis/new
    controller: App\Controller\AvisController::new

app_avis_user:
    path: '/avis/user'
    controller: 'App\Controller\AvisController::userAvis'
    methods: ['GET']

app_avis_edit:
    path: /avis/{id}/edit
    controller: App\Controller\AvisController::edit

app_avis_show:
    path: /avis/show/{id}
    controller: App\Controller\AvisController::show

app_avis_index:
    path: /avis/index
    controller: App\Controller\AvisController::index

app_avis_publish_homepage:
    path: /avis/{id}/publish-homepage
    controller: App\Controller\AvisController::publishToHomepage

app_avis_remove_from_homepage:
    path: /avis/{id}/remove-from-homepage
    controller: App\Controller\AvisController::removeFromHomepage

app_contact_index:
    path: /contact/index
    controller: App\Controller\ContactController::index
    methods: [GET]

app_contact_new:
    path: /contact/new
    controller: App\Controller\ContactController::new
    methods: [GET, POST]

app_contact_show:
    path: /contact/{id}
    controller: App\Controller\ContactController::show
    methods: [GET]

app_contact_edit:
    path: /contact/{id}/edit
    controller: App\Controller\ContactController::edit
    methods: [GET, POST]

app_contact_delete:
    path: /contact/{id}
    controller: App\Controller\ContactController::delete
    methods: [POST]

app_user_index:
    path: /user/index
    controller: App\Controller\UserController::index

cgu:
    path: /cgu
    controller: App\Controller\CGUController::index

legal_mentions:
    path: /mentions-legales
    controller: App\Controller\LegalController::mentionsLegales